server:
  port: 9190
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: visor-master-service
          uri: lb://visor-master-service
          predicates:
            - Path=/masters/**
         
                
        - id: visor-prs-service
          uri: lb://visor-prs-service
          predicates:
            - Path=/prs/**
     
                
        - id: visor-exams-service
          uri: lb://visor-exams-service
          predicates:
            - Path=/exams/**
         
        - id: visor-schoolapp-service
          uri: lb://visor-schoolapp-service
          predicates:
            - Path=/schools/**
  
        - id: visor-teacherapp-service
          uri: lb://visor-teacherapp-service
          predicates:
            - Path=/teachers/**
     
        - id: visor-adminapp-service
          uri: lb://visor-adminapp-service
          predicates:
            - Path=/admin/**
            
        - id: visor-studentapp-service
          uri: lb://visor-studentapp-service
          predicates:
            - Path=/students/**
            
        - id: visor-job-service
          uri: lb://visor-job-service
          predicates:
            - Path=/jobs/**
   
                
          

          
                
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    serviceUrl:
#      #defaultZone: http://164.52.202.187:8761/eureka/
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#   hostname: localhost
  

